language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
branches:
  only:
    - master
python:
  - 2.7

env:
  - TOX_ENV=py27-twlatest
  - TOX_ENV=pypy-twlatest
  - TOX_ENV=py27-tw150
  - TOX_ENV=pypy-tw150
  - TOX_ENV=py27-twtrunk
  - TOX_ENV=pypy-twtrunk

install:
  - pip install -U pip setuptools wheel
  - pip install tox codecov
  - |
    if [ "${TOX_ENV::5}" == "pypy-" ]; then
      git clone --depth 1 https://github.com/yyuu/pyenv.git ~/.pyenv
      PYENV_ROOT="$HOME/.pyenv"
      PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      pyenv install pypy2.7-5.8.0
      pyenv global pypy2.7-5.8.0
    fi

script:
  - tox -e $TOX_ENV

after_success:
  - codecov

notifications:
  email: false
  irc:
     channels: "chat.freenode.net#divmod"
     template:
       - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
     use_notice: true
