language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
branches:
  only:
    - master
python:
  - 2.6
  - 2.7
  - pypy
install:
  - pip install -e .
  - pip install coverage coveralls
script:
  - coverage run --branch --source=axiom $(which trial) axiom
  - coverage report -m
after_success:
  - coveralls
notifications:
  email: false
  irc:
     channels: "chat.freenode.net#divmod"
     template:
       - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
     use_notice: true
